name: Tests

on:
  push:
    branches: [ "feature/dockerize-application" ]
  pull_request:
    branches: [ "feature/dockerize-application" ]

    workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Run tests
      run: dotnet test --logger "console;verbosity=normal" --configuration Release